## Importing libraries

In [45]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt


from sklearn.ensemble import VotingClassifier
from sklearn import model_selection
from sklearn.metrics import confusion_matrix,classification_report
from sklearn. preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

from sklearn import preprocessing

from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC

### Loading dataset

In [11]:
data = pd.read_csv('dataset.csv')
data.head()

0   1   2  3  4   5  6  7    8  9  10  11
0  7  21  30  2  3  29  2  3   57  5   1   0
1  7  32  70  2  4  67  2  4  132  5   1   0
2  7  15   1  2  2   0  2  2    0  5   1   0
3  7  33  77  2  7  72  2  7  142  5   1   0
4  7  55  78  3  7  73  3  7  144  6   1   0

In [12]:
y = data.iloc[:,0].values
x = data.iloc[:,1:].values
x,y

(array([[  21,   30,    2, ...,    5,    1,    0],
        [  32,   70,    2, ...,    5,    1,    0],
        [  15,    1,    2, ...,    5,    1,    0],
        ...,
        [  82,   14,    7, ...,    1,    0,    1],
        [  30,   62,    2, ...,    3,    0,    0],
        [  30,   62,    2, ...,    7,    0, 9156]], dtype=int64),
 array([7, 7, 7, ..., 7, 7, 7], dtype=int64))

### Splitting the dataset into train and test

In [35]:
x_train,x_test,y_train,y_test = train_test_split(x,y)


### Scaling the dataset

In [36]:
mm = MinMaxScaler()
x_train_mm = mm.fit_transform(x_train)
x_test_mm = mm.transform(x_test)

In [37]:
x_train_mm,x_test_mm

(array([[9.75903614e-01, 1.00000000e+00, 1.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 1.88590288e-04],
        [3.37349398e-01, 6.36363636e-01, 2.85714286e-01, ...,
         3.00000000e-01, 0.00000000e+00, 9.42951438e-05],
        [1.92771084e-01, 6.81818182e-02, 2.85714286e-01, ...,
         7.00000000e-01, 0.00000000e+00, 5.43611504e-01],
        ...,
        [3.61445783e-01, 7.04545455e-01, 2.85714286e-01, ...,
         3.00000000e-01, 0.00000000e+00, 9.42951438e-05],
        [1.20481928e-02, 9.20454545e-01, 0.00000000e+00, ...,
         0.00000000e+00, 1.00000000e+00, 6.60066007e-04],
        [4.81927711e-02, 1.70454545e-01, 0.00000000e+00, ...,
         0.00000000e+00, 0.00000000e+00, 8.48656294e-04]]),
 array([[2.65060241e-01, 4.09090909e-01, 2.85714286e-01, ...,
         7.00000000e-01, 0.00000000e+00, 6.70721358e-01],
        [3.49397590e-01, 6.70454545e-01, 2.85714286e-01, ...,
         3.00000000e-01, 0.00000000e+00, 0.00000000e+00],
        [8.79518072e-01, 

In [49]:
target_names = ['DoSattack','dataProbing','malitiousControl', 'malitiousOperation','scan','spying', 'wrongSetUp','Normal']

## Defining models 

In [23]:
m1 = LogisticRegression(multi_class = 'multinomial', penalty = 'l2')
m2 = KNeighborsClassifier(n_neighbors = 9, metric = 'minkowski')
m3 = DecisionTreeClassifier()
m4 = RandomForestClassifier()
m5 = MultinomialNB()
m6 = LinearSVC()

In [30]:
hybrid = []
hybrid.append(('lr',m1))
hybrid.append(('knn',m2))
hybrid.append(('dtc',m3))
hybrid.append(('rf',m4))
hybrid.append(('nb',m5))
hybrid.append(('svc',m6))
hybrid

[('lr', LogisticRegression(multi_class='multinomial')),
 ('knn', KNeighborsClassifier(n_neighbors=9)),
 ('dtc', DecisionTreeClassifier()),
 ('rf', RandomForestClassifier()),
 ('nb', MultinomialNB()),
 ('svc', LinearSVC())]

In [39]:
ensemble = VotingClassifier(hybrid)
ensemble.fit(x_train_mm, y_train)
y_pred = ensemble.predict(x_test_mm)

c:\users\hebbar\appdata\local\programs\python\python39\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [40]:
y_pred

array([7, 7, 7, ..., 7, 7, 7], dtype=int64)

In [41]:
ensemble.score(x_test_mm,y_test)

0.9941667696941768

In [44]:
confusion_matrix(y_test, y_pred)

array([[  512,     0,     0,     0,     0,     0,     0,   512],
       [    0,    66,     0,     0,     0,     0,     0,     0],
       [    0,     0,   229,     0,     0,     0,     0,     5],
       [    0,     0,     0,   168,     0,     0,     0,     0],
       [    0,     0,     0,     0,   375,     0,     0,     0],
       [    0,     0,     0,     0,     0,   147,     0,     0],
       [    0,     0,     0,     0,     0,     0,    32,     0],
       [    1,     0,     0,     0,     1,     0,     0, 86925]],
      dtype=int64)

In [50]:
print(classification_report(y_test,y_pred,target_names=target_names))

                    precision    recall  f1-score   support

         DoSattack       1.00      0.50      0.67      1024
       dataProbing       1.00      1.00      1.00        66
  malitiousControl       1.00      0.98      0.99       234
malitiousOperation       1.00      1.00      1.00       168
              scan       1.00      1.00      1.00       375
            spying       1.00      1.00      1.00       147
        wrongSetUp       1.00      1.00      1.00        32
            Normal       0.99      1.00      1.00     86927

          accuracy                           0.99     88973
         macro avg       1.00      0.93      0.96     88973
      weighted avg       0.99      0.99      0.99     88973



In [51]:
rf_nb = []
rf_nb.append(('rf',m4))
rf_nb.append(('nb',m5))
rf_nb

[('rf', RandomForestClassifier()), ('nb', MultinomialNB())]

In [54]:
rf_nb_ensemble = VotingClassifier(rf_nb)
rf_nb_ensemble.fit(x_train_mm, y_train)
y_rf_nb_pred = rf_nb_ensemble.predict(x_test_mm)
rf_nb_ensemble.score(x_test_mm,y_test)

0.9942117271531813

In [57]:
print(classification_report(y_test,y_rf_nb_pred))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67      1024
           1       1.00      1.00      1.00        66
           2       1.00      1.00      1.00       234
           3       1.00      1.00      1.00       168
           4       0.99      1.00      1.00       375
           5       1.00      1.00      1.00       147
           6       1.00      1.00      1.00        32
           7       0.99      1.00      1.00     86927

    accuracy                           0.99     88973
   macro avg       1.00      0.94      0.96     88973
weighted avg       0.99      0.99      0.99     88973



In [56]:
confusion_matrix(y_test,y_rf_nb_pred)

array([[  512,     0,     0,     0,     0,     0,     0,   512],
       [    0,    66,     0,     0,     0,     0,     0,     0],
       [    0,     0,   234,     0,     0,     0,     0,     0],
       [    0,     0,     0,   168,     0,     0,     0,     0],
       [    0,     0,     0,     0,   375,     0,     0,     0],
       [    0,     0,     0,     0,     0,   147,     0,     0],
       [    0,     0,     0,     0,     0,     0,    32,     0],
       [    1,     0,     0,     0,     2,     0,     0, 86924]],
      dtype=int64)

In [61]:
rf_knn = []
rf_knn.append(('rf',m4))
rf_knn.append(('knn',m2))
rf_knn.append(('nb',m5))
rf_knn_ensemble = VotingClassifier(rf_knn)
rf_knn_ensemble.fit(x_train_mm, y_train)
y_rf_knn_pred = rf_nb_ensemble.predict(x_test_mm)
rf_knn_ensemble.score(x_test_mm,y_test)

0.9942229665179324